### ISSUE TITLE
neat, but...

### ISSUE THREAD

**Issue by stgarf** [haydenmkoch/alfred-dock-controller#1]
you know you can also just press `cmd+option+d` and don't need an entire workflow to show/hide the dock?

**Comment by haydenmkoch** [comment]
Yes, I'm aware! This stops it from revealing even if you hold your cursor on the edge of the screen there the dock is hidden 😉

**Comment by stgarf** [comment]
Ahhh more of a perma-hide w/ toggle via Alfred, got it! thanks for clarifying! 💯
